# Generated by Django 6.0.1 on 2026-04-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_options_task_assigned_to_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to_id',
            new_name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_username',
        ),
    ]
